### ISSUE TITLE
[BUG] - os_id collides with usage of script_id

### ISSUE THREAD

**Issue by stp-ip** [vultr/terraform-provider-vultr-community#92]
**Describe the bug**
It seems like one can't use script_id with os_id.

Aka setting the OS to say Ubuntu and at the same time requiring a startup script.

**To Reproduce**
Launch server with a os_id and script_id set.

**Expected behavior**
Use script with specific os chosen.

**Comment by ddymko** [comment]
@stp-ip 

I just submitted a pull request that address this issue 

https://github.com/vultr/terraform-provider-vultr/pull/91

Once this is merged in I will cut a new release
