### ISSUE TITLE
[BUG] - Not handling API rate limit gracefully

### ISSUE THREAD

**Issue by OJFord** [vultr/terraform-provider-vultr-community#97]
**Describe the bug**
It seems I've been playing with this provider enough to get rate-limited, and so now I can't `plan`/`refresh` at all because it hits the API faster than the hard rate-limit allows.

> Error: Error getting <resource> <ID>: Rate limit reached - please try your request again later.  Current rate limit: 3 requests/sec

**To Reproduce**
1. Create >`N` Vultr resources
1. `terraform apply`
1. Get rate-limited to `N` requests/sec
1. `terraform refresh`

**Expected behavior**
Detects the limit and backs off maybe?

**Additional context**

I haven't been using it *that* much!

**Comment by ddymko** [comment]
@OJFord you can set the `rate_limit` in the config

You define the time and it gets set to milliseconds. The default value is  650 milliseconds

https://github.com/vultr/terraform-provider-vultr/blob/84ec23dde2187dadeca23c4bc52e9f77cd6edd41/vultr/config.go#L46

https://github.com/vultr/terraform-provider-vultr/blob/master/docs/index.html.markdown

**Comment by OJFord** [comment]
@ddymko Thanks, maybe `1000` is a better default? i.e. ensure that we succeed whatever the request/second limit is?

Weird that I suddenly hit this (and consistently, I tried several times) if 3r/sec is standard - I suppose my round-trip time to Vultr servers suddenly dropped enough for some reason.

**Comment by ddymko** [comment]
@OJFord We beat terraform with really long build instructions we found that 650ms is the sweet spot for most cases. Also ran through the entire acceptance test suite with various timings and decided that is a good number for the default.

**Comment by hadleyrich** [comment]
I hit this also when trying to provision 5 servers, I had to increase my rate_limit config to 1500 to work around it.

**Comment by ddymko** [comment]
Hmmm might be related to latency on your locations

**Comment by ddymko** [comment]
We are looking to into a revamp of the api "v2" which will introduce a proper oauth flow. The V2 would also resolve a lot of inherited design choices & constraints we currently have with our API
